// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {app} from '../models';
import {license} from '../models';
import {notify} from '../models';
import {proxy} from '../models';
import {sku} from '../models';
import {uiauto} from '../models';

export function ActivateLicense(arg1:string):Promise<void>;

export function DeactivateLicense():Promise<void>;

export function GetDefaults():Promise<main.DesktopDefaults>;

export function GetDeviceID():Promise<string>;

export function GetJDAutomationStatus():Promise<app.JDAutomationStatus>;

export function GetLicenseServerURL():Promise<string>;

export function GetLicenseState():Promise<license.State>;

export function GetNotifyConfig():Promise<notify.Config>;

export function GetRequestLogs():Promise<Array<proxy.RequestLogEntry>>;

export function GetSKUList():Promise<sku.Snapshot>;

export function GetStatus():Promise<app.Status>;

export function InstallCert():Promise<app.Status>;

export function ResetSKUList():Promise<sku.Snapshot>;

export function SaveNotifyConfig(arg1:notify.Config):Promise<void>;

export function SetLicenseServerURL(arg1:string):Promise<void>;

export function StartJDAutomation(arg1:uiauto.CoordCycleOptions):Promise<app.JDAutomationStatus>;

export function StartProxy(arg1:main.DesktopStartOptions):Promise<app.Status>;

export function StopJDAutomation():Promise<app.JDAutomationStatus>;

export function StopProxy():Promise<app.Status>;

export function TestNotify(arg1:notify.Config):Promise<void>;

export function UninstallCert():Promise<app.Status>;

export function VerifyLicense():Promise<boolean>;
