// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {app} from '../models';
import {notify} from '../models';
import {proxy} from '../models';
import {sku} from '../models';
import {uiauto} from '../models';

export function FormatJSON(arg1:string):Promise<string>;

export function GetDefaults():Promise<main.DesktopDefaults>;

export function GetJDAutomationStatus():Promise<app.JDAutomationStatus>;

export function GetNotifyConfig():Promise<notify.Config>;

export function GetRequestLogs():Promise<Array<proxy.RequestLogEntry>>;

export function GetSKUList():Promise<sku.Snapshot>;

export function GetStatus():Promise<app.Status>;

export function InspectAutomation(arg1:string):Promise<string>;

export function InstallCert():Promise<app.Status>;

export function ReadTextFile(arg1:string):Promise<string>;

export function ResetSKUList():Promise<sku.Snapshot>;

export function RunAutomation(arg1:string):Promise<app.Status>;

export function SaveNotifyConfig(arg1:notify.Config):Promise<void>;

export function SelectJSONFile(arg1:string):Promise<string>;

export function StartJDAutomation(arg1:uiauto.CoordCycleOptions):Promise<app.JDAutomationStatus>;

export function StartProxy(arg1:main.DesktopStartOptions):Promise<app.Status>;

export function StopJDAutomation():Promise<app.JDAutomationStatus>;

export function StopProxy():Promise<app.Status>;

export function TestNotify(arg1:notify.Config):Promise<void>;

export function UninstallCert():Promise<app.Status>;

export function ValidateRulesText(arg1:string):Promise<main.RulesValidationResult>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
