// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FormatJSON(arg1) {
  return window['go']['main']['DesktopApp']['FormatJSON'](arg1);
}

export function GetDefaults() {
  return window['go']['main']['DesktopApp']['GetDefaults']();
}

export function GetJDAutomationStatus() {
  return window['go']['main']['DesktopApp']['GetJDAutomationStatus']();
}

export function GetRequestLogs() {
  return window['go']['main']['DesktopApp']['GetRequestLogs']();
}

export function GetSKUList() {
  return window['go']['main']['DesktopApp']['GetSKUList']();
}

export function GetStatus() {
  return window['go']['main']['DesktopApp']['GetStatus']();
}

export function InspectAutomation(arg1) {
  return window['go']['main']['DesktopApp']['InspectAutomation'](arg1);
}

export function InstallCert() {
  return window['go']['main']['DesktopApp']['InstallCert']();
}

export function ReadTextFile(arg1) {
  return window['go']['main']['DesktopApp']['ReadTextFile'](arg1);
}

export function ResetSKUList() {
  return window['go']['main']['DesktopApp']['ResetSKUList']();
}

export function RunAutomation(arg1) {
  return window['go']['main']['DesktopApp']['RunAutomation'](arg1);
}

export function SelectJSONFile(arg1) {
  return window['go']['main']['DesktopApp']['SelectJSONFile'](arg1);
}

export function StartJDAutomation(arg1) {
  return window['go']['main']['DesktopApp']['StartJDAutomation'](arg1);
}

export function StartProxy(arg1) {
  return window['go']['main']['DesktopApp']['StartProxy'](arg1);
}

export function StopJDAutomation() {
  return window['go']['main']['DesktopApp']['StopJDAutomation']();
}

export function StopProxy() {
  return window['go']['main']['DesktopApp']['StopProxy']();
}

export function UninstallCert() {
  return window['go']['main']['DesktopApp']['UninstallCert']();
}

export function ValidateRulesText(arg1) {
  return window['go']['main']['DesktopApp']['ValidateRulesText'](arg1);
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['DesktopApp']['WriteTextFile'](arg1, arg2);
}
