// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['DesktopApp']['ActivateLicense'](arg1);
}

export function DeactivateLicense() {
  return window['go']['main']['DesktopApp']['DeactivateLicense']();
}

export function GetDefaults() {
  return window['go']['main']['DesktopApp']['GetDefaults']();
}

export function GetDeviceID() {
  return window['go']['main']['DesktopApp']['GetDeviceID']();
}

export function GetJDAutomationStatus() {
  return window['go']['main']['DesktopApp']['GetJDAutomationStatus']();
}

export function GetLicenseServerURL() {
  return window['go']['main']['DesktopApp']['GetLicenseServerURL']();
}

export function GetLicenseState() {
  return window['go']['main']['DesktopApp']['GetLicenseState']();
}

export function GetNotifyConfig() {
  return window['go']['main']['DesktopApp']['GetNotifyConfig']();
}

export function GetRequestLogs() {
  return window['go']['main']['DesktopApp']['GetRequestLogs']();
}

export function GetSKUList() {
  return window['go']['main']['DesktopApp']['GetSKUList']();
}

export function GetStatus() {
  return window['go']['main']['DesktopApp']['GetStatus']();
}

export function InstallCert() {
  return window['go']['main']['DesktopApp']['InstallCert']();
}

export function ResetSKUList() {
  return window['go']['main']['DesktopApp']['ResetSKUList']();
}

export function SaveNotifyConfig(arg1) {
  return window['go']['main']['DesktopApp']['SaveNotifyConfig'](arg1);
}

export function SetLicenseServerURL(arg1) {
  return window['go']['main']['DesktopApp']['SetLicenseServerURL'](arg1);
}

export function StartJDAutomation(arg1) {
  return window['go']['main']['DesktopApp']['StartJDAutomation'](arg1);
}

export function StartProxy(arg1) {
  return window['go']['main']['DesktopApp']['StartProxy'](arg1);
}

export function StopJDAutomation() {
  return window['go']['main']['DesktopApp']['StopJDAutomation']();
}

export function StopProxy() {
  return window['go']['main']['DesktopApp']['StopProxy']();
}

export function TestNotify(arg1) {
  return window['go']['main']['DesktopApp']['TestNotify'](arg1);
}

export function UninstallCert() {
  return window['go']['main']['DesktopApp']['UninstallCert']();
}

export function VerifyLicense() {
  return window['go']['main']['DesktopApp']['VerifyLicense']();
}
